import { Elysia, t } from "elysia";
import { generatePdfFromUrl } from "../lib/pdf";
import { readCache, writeCache } from "../lib/cache";
import { buildResumeHtml } from "../lib/resume-html";

/**
 * GET /resume.pdf
 *
 * Smart-cached PDF download of the /resume page.
 *
 * Cache strategy:
 *   1. Check if tmp/pdf-cache/resume.pdf exists.
 *   2. If the cache is younger than CACHE_TTL_MS  → serve from disk (HIT).
 *   3. Otherwise → launch Playwright, render /resume, save to disk (MISS).
 */

const CACHE_KEY = "resume";
// Cache is valid for 24 hours; bump this or delete the file to force a regen.
const CACHE_TTL_MS = 24 * 60 * 60 * 1000;

export const resumePdfRoute = new Elysia()
  .get(
    "/resume.pdf",
    async ({ server }) => {
      const newerThan = Date.now() - CACHE_TTL_MS;
      const cached = readCache(CACHE_KEY, newerThan);

      if (cached.hit && cached.data) {
        console.log("📄 resume.pdf → cache HIT");
        return new Response(new Uint8Array(cached.data), {
          headers: {
            "Content-Type": "application/pdf",
            "Content-Disposition": 'attachment; filename="resume.pdf"',
            "X-Cache": "HIT",
          },
        });
      }

      console.log("🖨  resume.pdf → cache MISS – generating via Playwright…");

      // Derive the base URL from the running server
      const hostname = server?.hostname ?? "localhost";
      const port = server?.port ?? 3000;
      const resumeUrl = `http://${hostname}:${port}/resume`;

      const pdf = await generatePdfFromUrl({
        url: resumeUrl,
        format: "A4",
        printBackground: true,
        margin: { top: "0", right: "0", bottom: "0", left: "0" },
        extraWaitMs: 800,
      });

      writeCache(CACHE_KEY, pdf);
      console.log("✅ resume.pdf generated & cached");

      return new Response(new Uint8Array(pdf), {
        headers: {
          "Content-Type": "application/pdf",
          "Content-Disposition": 'attachment; filename="resume.pdf"',
          "X-Cache": "MISS",
        },
      });
    },
    {
      detail: {
        summary: "Download resume PDF",
        description:
          "Returns a pixel-perfect PDF of the /resume page generated by a headless Chromium browser. The result is cached on the filesystem for 24 hours; subsequent requests are served instantly from cache. Delete `tmp/pdf-cache/resume.pdf` or decrement the TTL to force regeneration.",
        tags: ["Resume"],
      },
    }
  );
